#!/bin/bash

ID=$(id -u)

if [ $ID -ne 0 ]; then

echo -e "\e[31m Please use root account or sudo priveledge to proceed further \e[0m"
exit 1

fi

yum install nginx -y    >> /tmp/frontend.log
systemctl enable nginx  >> /tmp/frontend.log
systemctl start nginx   >> /tmp/frontend.log
